apiVersion: apps/v1
kind: Deployment
metadata:
  name: passion-mansour-ide-frontend-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: passion-mansour-ide-frontend
  template:
    metadata:
      labels:
        app: passion-mansour-ide-frontend
    spec:
      containers:
        - name: passion-mansour-ide-frontend
          image: passion-mansour-ide-frontend/passion-mansour-ide-frontend:tag
          ports:
            - containerPort: 3000

---
apiVersion: v1
kind: Service
metadata:
  name: passion-mansour-ide-frontend
spec:
  type: LoadBalancer
  selector:
    app: passion-mansour-ide-frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
