apiVersion: v1
kind: Secret
metadata:
  name: my-secret
data:
  VITE_API_BASE_URL: aHR0cDovL2VjMi01NC0xODAtMTQxLTI5LmFwLW5vcnRoZWFzdC0yLmNvbXB1dGUuYW1hem9uYXdzLmNvbS9hcGk=
  VITE_WEBSOCKET_URL: aHR0cDovL2VjMi01NC0xODAtMTQxLTI5LmFwLW5vcnRoZWFzdC0yLmNvbXB1dGUuYW1hem9uYXdzLmNvbS93ZWJzb2NrZXQ=